# Generated by Django 2.1.1 on 2018-10-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('home_phone', models.CharField(max_length=200)),
                ('cell_phone', models.CharField(max_length=200)),
                ('home_address', models.CharField(max_length=200)),
                ('home_city', models.CharField(max_length=200)),
                ('home_state', models.CharField(max_length=200)),
                ('home_zip', models.IntegerField(max_length=6)),
                ('work_phone', models.CharField(max_length=200)),
                ('work_address', models.CharField(max_length=200)),
                ('work_city', models.CharField(max_length=200)),
                ('work_state', models.CharField(max_length=200)),
                ('work_zip', models.IntegerField(max_length=6)),
                ('birth_date', models.CharField(max_length=200)),
            ],
        ),
    ]
