# Generated by Django 2.1.1 on 2018-10-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='home_zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='work_zip',
            field=models.IntegerField(),
        ),
    ]
