# Generated by Django 2.1.1 on 2018-10-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181013_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='home_zip',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='work_zip',
            field=models.CharField(max_length=200),
        ),
    ]
