# Generated by Django 2.1.1 on 2018-10-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181013_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='birth_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='home_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='home_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='home_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='home_state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='home_zip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='middle_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='work_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='work_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='work_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='work_state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='work_zip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
