# Generated by Django 2.1.1 on 2018-10-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181014_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='id',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
