# Generated by Django 2.1.1 on 2018-10-17 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_type', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='phone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_type', models.CharField(blank=True, max_length=200, null=True)),
                ('area_code', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Contacts')),
            ],
        ),
    ]
